#!/usr/bin/env python3
"""Convert a JSON allocator trace into a MAVLink tlog or live stream.

This script reads a trace generated by the allocator (the same files that
end up in the ``runs/`` directory) and emits MAVLink messages that
approximate the vehicle's position and yaw.  It can either write a
.tlog file that you can open in Mission Planner's "Review a Log" window,
or stream the packets out of a TCP/UDP port for live plotting.

Usage examples:

    # produce a tlog you can open in MP
    python scripts/trace_to_tlog.py --trace runs/trace_repel_demo_wall.json \
        --out runs/trace_repel_demo_wall.tlog

    # stream into mavlink-router (port 5760) for live viewing
    python scripts/trace_to_tlog.py --trace runs/trace_repel_demo_wall.json \
        --out tcp:127.0.0.1:5760

The resulting MAVLink messages are:

* HEARTBEAT at the start
* LOCAL_POSITION_NED carrying x,y from the trace (meters)
* ATTITUDE carrying a yaw computed from the trace, with zero roll/pitch

Timestamps are derived from the trace's ``hist.t`` field (seconds).
"""

import argparse
import json
import math
import time

from pymavlink import mavutil


def build_connection(out_path):
    """Return a MAVLink connection or writer depending on ``out_path``.

    If ``out_path`` ends with ``.tlog`` or ``.bin`` we treat it as a file and
    return a ``MAVLink`` object that writes to that file; otherwise we call
    ``mavutil.mavlink_connection`` and return whatever it gives us (a connection
    object with a ``mav`` attribute).
    """
    if out_path.endswith('.tlog') or out_path.endswith('.bin'):
        f = open(out_path, 'wb')
        # create a MAVLink object that writes to the file
        return mavutil.mavlink.MAVLink(f), f
    else:
        # normal network connection
        m = mavutil.mavlink_connection(out_path)
        return m, None


def main():
    p = argparse.ArgumentParser(description="Stream or dump trace as MAVLink")
    p.add_argument('--trace', required=True,
                   help='JSON trace file with hist.* arrays')
    p.add_argument('--out', default='tcp:127.0.0.1:5760',
                   help='MAVLink target (tcp/udp or .tlog filepath)')
    p.add_argument('--rate', type=float, default=None,
                   help='override playback rate (Hz)')
    p.add_argument('--loop', action='store_true',
                   help='loop playback indefinitely')
    args = p.parse_args()

    with open(args.trace, 'r', encoding='utf-8') as f:
        d = json.load(f)
    h = d.get('hist', {})
    t = h.get('t', [])
    if not t:
        raise SystemExit('trace contains no hist.t values')

    # optional state arrays
    x = h.get('x', [])
    y = h.get('y', [])
    z = h.get('z', []) if 'z' in h else [0]*len(t)
    yaw = h.get('yaw_deg', [])

    m, fileobj = build_connection(args.out)
    if isinstance(m, mavutil.mavlink.MAVLink):
        mv = m
        def send(msg):
            mv.send(msg)
    else:
        mv = m.mav
        def send(msg):
            mv.send(msg)

    print(f"output -> {args.out}")
    # heartbeat message may return None with some MAVLink types; guard against it
    hb = mv.heartbeat_send(mavutil.mavlink.MAV_TYPE_QUADROTOR,
                             mavutil.mavlink.MAV_AUTOPILOT_INVALID,
                             0, 0, 0)
    if hb is not None:
        send(hb)

    start_time = time.time()
    idx = 0
    rate = args.rate
    while True:
        if idx >= len(t):
            if args.loop:
                idx = 0
                start_time = time.time()
            else:
                break
        if rate is None:
            target = start_time + t[idx]
        else:
            target = start_time + idx / rate
        now = time.time()
        if now < target:
            time.sleep(target - now)
        tx = float(x[idx]) if idx < len(x) else 0.0
        ty = float(y[idx]) if idx < len(y) else 0.0
        tz = float(z[idx]) if idx < len(z) else 0.0
        msg = mv.local_position_ned_send(int(t[idx]*1000), tx, ty, tz, 0, 0, 0)
        if msg is not None:
            send(msg)
        yaw_rad = math.radians(float(yaw[idx]) if idx < len(yaw) else 0.0)
        msg2 = mv.attitude_send(int(t[idx]*1000), 0.0, 0.0, yaw_rad, 0, 0, 0)
        if msg2 is not None:
            send(msg2)
        idx += 1

    if fileobj is not None:
        fileobj.close()
    print('finished')


if __name__ == '__main__':
    main()
